# Generated by Django 5.2 on 2025-05-27 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_checkout_is_canceled_checkout_is_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='payment.order'),
        ),
    ]
