# Generated by Django 5.2 on 2025-05-27 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0052_order'),
        ('payment', '0005_remove_checkout_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='is_failed',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='checkout',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='hotels.order'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
