# Generated by Django 5.2 on 2025-05-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_order_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='booked',
        ),
    ]
