# Generated by Django 5.2 on 2025-06-06 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0053_delete_order'),
        ('payment', '0011_remove_order_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booked',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='hotels.booked'),
        ),
    ]
