# Generated by Django 5.2 on 2025-05-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0048_alter_hotel_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='district_names',
        ),
    ]
