# Generated by Django 5.2 on 2025-05-02 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0049_remove_hotel_district_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='district_names',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='hotels.district'),
        ),
    ]
