# Generated by Django 5.2 on 2025-05-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0050_hotel_district_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='is_cencelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booked',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
    ]
