# Generated by Django 5.2 on 2025-05-27 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0052_order'),
        ('payment', '0007_remove_checkout_order_checkout_is_canceled_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
